stow -vt ~ bash/
stow -vt ~ nvim/
stow -vt ~ starship/
stow -vt ~ sway/
stow -vt ~ swayimg/
stow -vt ~ waybar/
stow -vt ~ wezterm/
stow -vt ~ wlogout/
stow -vt ~ wofi/
stow -vt ~ yazi/
stow -vt ~ mako/
stow -vt ~ waypaper/
